# -*- coding: utf-8 -*-
from django import forms


class OfferForm(forms.Form):

    _job_functions = (
        ('', ''),
        ('Administration - Services généraux', (
            ("10101", "Documentaliste"),
            ("10102", "Secrétaire/Assistante de Direction"),
            ("10103", "Services Généraux"),
        )),
        ('Gestion - Comptabilité - Finance', (
            ("10201", "DAF/Direction financière"),
            ("10202", "Direction Comptable"),
            ("10203", "Analyse Financière"),
            ("10205", "Comptables"),
            ("10206", "Consolidation"),
            ("10207", "Contrôle de Gestion"),
            ("10208", "Credit management"),
            ("10209", "Organisation comptable"),
            ("10210", "Trésorerie"),
            ("10211", "Cambiste - Trader"),
            ("10212", "Cadres Bancaires"),
            ("10213", "Gestion patrimoniale"),
        )),
        ('Audit', (
            ("10301", "Audit Externe"),
            ("10302", "Audit Interne"),
        )),
        ('Conseil', (
            ("10401", "Conseil en Droit - Fiscalité"),
            ("10402", "Conseil en Finances"),
            ("10403", "Conseil en Management - Stratégie"),
            ("10404", "Conseil en Marketing - Commercial - Communication"),
            ("10405", "Conseil aux PME - PMI"),
            ("10406", "Conseil en RH"),
            ("10407", "Conseil en Stratégie NTIC - Nouvelle économie"),
            ("10408", "Conseil en Système d'Information - Organisation"),
        )),
        ('Juridique Fiscal', (
            ("10501", "Direction Juridique"),
            ("10502", "Cadres Juridiques toutes spécialités"),
            ("10503", "Conseil Juridique/Avocat"),
            ("10504", "Fiscaliste"),
            ("10505", "Services Contentieux"),
            ("10506", "Expertise"),
        )),
        ('Ressources Humaines - Personnel - Formation', (
            ("10601", "DRH"),
            ("10602", "RRH/Chef du personnel"),
            ("10603", "Formation"),
            ("10604", "Gestion de carrières"),
            ("10605", "Gestion du personnel/Paie"),
            ("10606", "Recrutement"),
            ("10607", "Relations sociales"),
            ("10608", "Rémunération"),
        )),
        ('Etudes - Recherche', (
            ("20101", "Direction R & D"),
            ("20102", "Direction Scientifique"),
            ("20103", "Brevets/Marques"),
            ("20104", "Chef de Projet/Ingénierie"),
            ("20105", "Etudes/Bureau d'Etudes"),
            ("20106", "Ingénieur R & D/Chercheur"),
            ("20107", "Recherche/Laboratoire"),
            ("20108", "Statistiques"),
            ("20203", "Affaires Réglementaires"),
            ("20207", "Médico-Marketing"),
            ("20208", "Information Médicale/Formation/Pharmacovigilance"),
            ("20209", "Médecin du travail"),
        )),
        ('Santé (Médical) - Social', (
            ("20231", "Direction d'établissement"),
            ("20232", "Activités sociales"),
            ("20233", "Infirmier/Infirmière"),
            ("20234", "Dentiste"),
            ("20235", "Médecin/Chirurgien généraliste"),
            ("20236", "Médecin/Chirurgien spécialiste"),
            ("20238", "Paramédical de soin"),
            ("20239", "Paramédicale de rééducation"),
            ("20240", "Paramédical médico-technique"),
            ("20241", "Pharmacien"),
            ("20242", "Sage-femme"),
            ("20243", "Vétérinaire/soins animaliers"),
            ("20244", "Autres"),
        )),
        ('Santé (Industrie)', (
            ("20261", "Directions"),
            ("20264", "Recherche & Développement clinique"),
            ("20267", "Prix/Remboursement/Economie"),
            ("20268", "Qualité"),
            ("20270", "Autres"),
        )),
        ('Logistique - Achat - Stock - Transport', (
            ("20301", "Direction Logistique/Transport"),
            ("20302", "Direction Achats"),
            ("20303", "Achats/Approvisionnements"),
            ("20304", "Gestion de stocks/Magasins"),
            ("20305", "Logisticien"),
            ("20306", "Ordonnancement/Planning"),
            ("20307", "Organisation Industrielle"),
        )),
        ('Production - Maintenance - Qualité - Sécurité - Environnement', (
            ("20401", "Direction d'Usine"),
            ("20402", "Direction Industrielle"),
            ("20403", "Direction Production"),
            ("20404", "Direction Technique"),
            ("20405", "Chef de Fabrication/Production"),
            ("20406", "Contrôle/Assurance Qualité"),
            ("20407", "Environnement/Sécurité"),
            ("20408", "Gestion de Production"),
            ("20409", "Maintenance/Entretien"),
            ("20410", "Méthodes/Process/Industrialisation"),
            ("20411", "Production"),
            ("20412", "S.A.V."),
            ("20413", "Travaux Neufs/Chantiers"),
        )),
        ('Systèmes d\'informations / télécom', (
            ("20501", "Direction"),
            ("20503", "Chef de Projet / MOE"),
            ("20504", "Consultant / Audit / AMOA"),
            ("20505", "Analyste Programmeur"),
            ("20507", "Exploitation / Production"),
            ("20510", "Système / Réseaux / Base de Données"),
            ("20514", "Service utilisateurs / Hotliner"),
            ("20517", "Ingénieur Avant-Vente"),
            ("20518", "Ingénieur Etudes / Développement"),
            ("20519", "Architecture/Urbanisme"),
            ("20520", "Directeur de Projet/MOA"),
            ("20521", "Ingénieur Télécom"),
            ("20522", "Qualité/Méthodes"),
            ("20523", "Sécurité"),
        )),
        ('Internet – E-commerce', (
            ("20701", "Direction"),
            ("20703", "Contenus / Partenariats"),
            ("20705", "Webmaster / Webdesign"),
            ("20707", "Référencement / Traffic Management"),
            ("20708", "Webplanner"),
        )),
        ('Commercial - Vente', (
            ("30101", "Direction commerciale/Dvlpt/Stratégie"),
            ("30102", "Direction des ventes/Chef des ventes"),
            ("30103", "Administration des ventes"),
            ("30104", "Assistanat Commercial"),
            ("30105", "Chef d'agence/Resp. magasin"),
            ("30106", "Chef de rayon/Chef de Secteur"),
            ("30107", "Commercial"),
            ("30108", "Grands-Comptes"),
            ("30109", "Ingénieur d'affaires"),
            ("30110", "Télévente"),
            ("30111", "Ingénieur commercial"),
            ("30112", "Technico-commercial"),
            ("30113", "Commercial/Ingénieur Technico-Commercial"),
            ("30114", "Vente"),
        )),
        ('Export', (
            ("30401", "Direction Export/Dir. internationale"),
            ("30402", "Area manager"),
            ("30403", "Chef de zone export"),
        )),
        ('Marketing', (
            ("30501", "Direction Marketing"),
            ("30502", "Chef de Groupe/Marché"),
            ("30503", "Chef de Produit"),
            ("30504", "Marketing Direct"),
            ("30505", "Marketing Etudes"),
            ("30506", "Marketing opérationnel/Promo ventes"),
            ("30507", "Relation clients - Consommateurs - SAV"),
        )),
        ('Communication - Création', (
            ("30801", "Direction de la communication"),
            ("30802", "Direction Clientèle"),
            ("30803", "Chef de Publicité"),
            ("30804", "Communication interne"),
            ("30805", "Presse"),
            ("30806", "Communication Externe"),
            ("30807", "Direction Artistique"),
            ("30808", "Direction Création"),
            ("30809", "Conception - Rédaction"),
            ("30810", "Création - Graphisme - PAO"),
            ("30811", "Journalisme"),
            ("30812", "Relations Presse - Relations Publiques"),
            ("30813", "Traduction - Interprétariat"),
        )),
        ('Direction générale - Direction centre de profits', (
            ("40001", "P.D.G."),
            ("40002", "D.G./D.G.A."),
            ("40003", "Direction Filiale/Centre de Profits"),
            ("40004", "Secrétaire Général"),
        )),
    )

    _job_sectors = (
        ('', ''),
        ('Construction BTP', (
            ("10001", "Génie Civil/TP"),
            ("10002", "Gros oeuvre"),
            ("10003", "Maisons individuelles"),
            ("10004", "Production matériaux construction"),
            ("10005", "Second oeuvre"),
            ("10006", "Société immobilière/Promoteur"),
        )),
        ('Immobilier', (
            ("15001", "Société immobilière"),
            ("15002", "Promoteur"),
            ("15003", "SCPI (Société Civile de Placement Immobilier)"),
            ("15004", "Habitation - Gestion locative"),
        )),
        ('Banque/Assurance/Finance', (
            ("20001", "Banque/Etablissement financier/Crédit Bail..."),
            ("20002", "Bourse"),
            ("20003", "Capital Risque"),
            ("20004", "Compagnie Assurance/Courtier"),
        )),
        ('Distribution', (
            ("30001", "Automobile/Moto"),
            ("30002", "Bricolage/Jardin/Décoration/Ameublement"),
            ("30003", "Centrale d'achats"),
            ("30004", "Commerce alimentaire"),
            ("30005", "Disques/Livres"),
            ("30006", "Habillement/Produit Luxe/Mode/Sport"),
            ("30007", "HiFi/Vidéo/Informatique/Micro/Telecom…"),
            ("30008", "Hyper/Super/Grand Magasin"),
            ("30009", "Import/Export"),
            ("30010", "Négoce/Commerce gros industriel"),
            ("30011", "V.P.C."),
        )),
        ('Informatique / Télécom / Internet', (
            ("40001", "Constructeur"),
            ("40002", "Editeur de logiciels"),
            ("40003", "Internet"),
            ("40004", "Opérateur / Infogérance / Hébergeur / FAI"),
            ("40005", "Services Informatiques"),
            ("40006", "Conseil/Audit"),
        )),
        ('Services publics/Administrations', (
            ("50001", "Armée/Défense/Sécurité"),
            ("50002", "Administrations/Institutions"),
            ("50003", "Collectivités locales/Territoriales"),
            ("50004", "Enseignement/Animation/Recherche"),
            ("50006", "Affaires étrangères/International"),
            ("50007", "Dévelop.t économique/Commerce/Organisme Consulaire"),
            ("50008", "Services santé/Action sociale"),
            ("50009", "Affaires culturelles"),
            ("50010", "Services Techniques"),
            ("50011", "Droit/Justice"),
            ("50012", "Economie/Finances"),
            ("50013", "Environnement/Agriculture"),
            ("50014", "Industries/Energies"),
            ("50015", "Informatique/Télécommunications"),
            ("50016", "Politique de la ville/Logement"),
            ("50017", "Restauration collective"),
            ("50018", "Sport/Loisirs/Tourisme"),
            ("50019", "Autres"),
        )),
        ('Industries', (
            ("60001", "Aéronautique/Spatial"),
            ("60002", "Agriculture"),
            ("60003", "Agroalimentaire"),
            ("60004", "Armement"),
            ("60005", "Art de la table/Décoration"),
            ("60006", "Auto-Moto-Cycles"),
            ("60007", "Biens d'équipement de la maison"),
            ("60008", "Bureautique"),
            ("60009", "Chimie/Parachimie"),
            ("60010", "Construction Navale"),
            ("60011", "Cosmétique/Parfumerie/Produit d'hygiène"),
            ("60012", "Disque/Ciné/Vidéo/Radio/Photo/TV"),
            ("60013", "Eau/Gaz/Electricité/Chauffage"),
            ("60014", "Edition/Imprimerie"),
            ("60015", "Electricité"),
            ("60016", "Electromécanique"),
            ("60017", "Electroménager"),
            ("60018", "Electronique"),
            ("60019", "Emballage"),
            ("60020", "Energie Nucléaire"),
            ("60021", "Environnement"),
            ("60022", "Equipement industriel"),
            ("60023", "Equipementier auto-moto-cycles"),
            ("60024", "Extraction/Mines"),
            ("60025", "Ferroviaire"),
            ("60026", "Horlogerie/Joaillerie/Bijouterie"),
            ("60027", "Instrumentation"),
            ("60028", "Matériel d'éclairage"),
            ("60029", "Matériel Médical / Diagnostic"),
            ("60030", "Mécanique/Machine Outil"),
            ("60031", "Métallurgie"),
            ("60032", "Meuble/Travail du Bois"),
            ("60033", "Optique"),
            ("60034", "Papier/Carton"),
            ("60035", "Peinture/Encre"),
            ("60036", "Pétrole (production/distribution)"),
            ("60037", "Pharmacie/Parapharmacie/Biotechnologie"),
            ("60038", "Plasturgie/Plastique/Composite"),
            ("60039", "Presse"),
            ("60040", "Produits de Loisir/Jouets/Jeux"),
            ("60041", "Produits d'entretien/Détergents"),
            ("60042", "Robotique"),
            ("60043", "Sidérurgie"),
            ("60044", "Tabac"),
            ("60045", "Textile/Habillement/Chaussure"),
            ("60046", "Verre/Céramique"),
        )),
        ('Services', (
            ("70001", "Agence pub/Marketing Direct/Communication"),
            ("70002", "Association"),
            ("70003", "Autres Services aux collectivités/Entreprises"),
            ("70004", "Autres Services aux Particuliers"),
            ("70005", "Cabinet Comptable/Audit"),
            ("70006", "Conseil aux entreprises"),
            ("70007", "Conseil Juridique/Cabinet d'avocats"),
            ("70008", "Hôtellerie/Restauration"),
            ("70009", "Ingénierie/Bureau d'Etudes"),
            ("70010", "Intérim"),
            ("70011", "Location Véhicules/Diverse"),
            ("70012", "Loisirs/Culture/Cinéma"),
            ("70013", "Maintenance industrielle"),
            ("70014", "Nettoyage industriel/Sécurité"),
            ("70015", "Services santé/Cliniques"),
            ("70016", "Recherche"),
            ("70017", "Salons/Congrès/Manifestations"),
            ("70018", "Tourisme/Voyages"),
            ("70019", "Transports - Messagerie Express"),
        )),
    )

    _contracts = (
        ('CDI', 'CDI'),
        ('CDD', 'CDD'),
        ('Stage', 'Stage'),
        ('Alternance', 'Alternance/Apprentissage'),
        ('Freelance', 'Freelance'),
    )

    name_company = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control input-small'}),
        label=u'Nom de l\'entreprise',
    )
    localisation = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control input-small'}),
        label=u'Localisation de l\'offre',
    )
    localisation_code = forms.CharField(
        required=True,
        widget=forms.HiddenInput(),
    )
    localisation_city = forms.CharField(
        required=True,
        widget=forms.HiddenInput(),
    )
    localisation_province = forms.CharField(
        required=True,
        widget=forms.HiddenInput(),
    )
    localisation_country = forms.CharField(
        required=True,
        widget=forms.HiddenInput(),
    )
    contract = forms.ChoiceField(
        choices=_contracts,
        required=True,
        widget=forms.Select(attrs={'class': 'form-control input-small'}),
        label=u'Type de contrat',
    )
    industry = forms.ChoiceField(
        choices=_job_sectors,
        required=True,
        widget=forms.Select(attrs={'class': 'form-control input-small'}),
        label=u'Secteur d\'activité',
    )
    function = forms.ChoiceField(
        choices=_job_functions,
        required=True,
        widget=forms.Select(attrs={'class': 'form-control input-small'}),
        label=u'Poste de l\'offre',
    )
    title = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control input-small'}),
        label=u'Titre de l\'offre',
    )
    description = forms.CharField(
        required=True,
        widget=forms.Textarea(attrs={'class': 'form-control'}),
        label=u'Description de l\'offre',
    )


class ContactForm(forms.Form):

    _phone_re = r'^0[1-6]{1}(([0-9]{2}){4})|((\s[0-9]{2}){4})|((-[0-9]{2}){4})$'
    _employee_choices = (
        (u'1', u'1 à 5'),
        (u'2', u'6 à 20'),
        (u'3', u'20 à 100'),
        (u'4', u'100 à 249'),
        (u'5', u'plus de 250'),
    )

    name_company = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control input-small'}),
        label=u'Nom de l\'entreprise',
    )
    num_employees = forms.ChoiceField(
        choices=_employee_choices,
        required=True,
        widget=forms.Select(attrs={'class': 'form-control input-small'}),
        label=u'Nombre d\'employés',
    )
    lastname_contact = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control input-small'}),
        label=u'Nom',
    )
    givenname_contact = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control input-small'}),
        label=u'Prénom',
    )
    phone_contact = forms.RegexField(
        regex=_phone_re,
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control input-small'}),
        label='Numéro de téléphone',
    )
    email = forms.EmailField(
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control input-small'}),
        label=u'Email',
    )
    confirm_email = forms.EmailField(
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control input-small'}),
        label=u'Confirmer l\'Email',
    )
